### PR TITLE
Dark theme for checkboxes in QListView and QTreeView

### PR DESCRIPTION
**Pull request by nikita-y**

### CODE REVIEW

**Comment by ColinDuquesnoy** [comment]
Thank you! That looks good.

Just one question: what is the purpose of the second commit and how is it related to this PR? Shouldn't this be another PR?

**Comment by nikita-y** [comment]
Hey! Yes it's for the another PR.
It basically fills the slider part before the handle with blue color
[image: Inline image 1]

Regards.
Nikita Yakovlev.
Phone: +1 (917) 688-6168
Email: nikinweb@gmail.com

**Comment by ColinDuquesnoy** [comment]
@nikita-y The attached image does not show up here on github. Easiest way to attach images on github is to just drag & drop it on the comment text area.

Since the second commit is for a separate PR, please remove that commit from this PR and submit another one.

**Comment by nikita-y** [comment]
Hey @ColinDuquesnoy The commit has been reverted.

**Comment by ColinDuquesnoy** [comment]
Thank you!

**Pull request merged**
