### PR TITLE
Add light theme to Qdarkstyle

### PR DESCRIPTION
**Pull request by juanis2112**
This PR adds everything needed for having a light theme in QDarkstyle

Screenshot 2021-03-23 at 3 54 28 PM
Screenshot 2021-03-23 at 3 54 38 PM
Screenshot 2021-03-23 at 3 54 49 PM
Screenshot 2021-03-23 at 3 55 02 PM
Screenshot 2021-03-23 at 3 55 22 PM

### CODE REVIEW

**Comment by juanis2112** [comment]
I rebased this with develop in order to include the last merged changes. I think this one is ready for review @dpizetta

**Comment by ccordoba12** [comment]
@dpizetta, I merged again with develop to fix the merge conflicts with your latest changes.

**Comment by juanis2112** [comment]
Hi Daniel!

I'm posting here a screenshot of the light theme in Spyder and things are working fine! (The cantered tabs in editor and console will be fixed in Spyder but they are not related to QDarkstyle).
Could you please release 3.0 so @ccordoba12 can make the release tomorrow? 

Screenshot 2021-03-31 at 5 53 07 PM

**Comment by dpizetta** [comment]
@juanis2112 tks, it is already released :) Please check the buttons I mentioned in #260. 

Tks for your collaboration!

**Comment by ccordoba12** [comment]
Thanks a lot for your help @dpizetta! It's been great collaborating with you on getting this release done!

**Pull request merged**
