### PR TITLE
Fixed incorrect QGroupBox indicator and QDateTimeEdit drop-down

### LINKED ISSUE #218: QGroupBox indicator size is incorrect
- QDarkStyle: latest master
- OS: Windows 10
- Qt v5.12.2
Language: C++

When focused, QGroupBox's checkbox (indicator sub-element) is displayed in smaller size than any normal checkbox:
qds_1_focused_groupbox

Expected Result:
The icon of the indicator sub-element of a QGroupBox should look the same way any normal checkbox does. This is how checkboxes look in default Win10 theme (dropdowns are related to another issue I'll file later):
qds_4_default_win10_theme

### PR DESCRIPTION
**Pull request by tsilia**
This commit fixes #218, #219, #220.

Before:
before
After:
after
The size and icon of the groupbox's indicator are now the same as those of normal checkbox.
QDateTimeEdit's dropdown now looks the same as dropdown for QDateEdit and QComboBox.

### CODE REVIEW

**Comment by tsilia** [comment]
@dpizetta
Somehow I can't get running the python scripts on Window and Linux. So I've included style.qss auto-generated with the qtsass compiler. You can review it, and if you feel that lost formatting is a disaster let me know pls. I'll gladly update the PR and remove the auto-generated file so that you can regenerate it yourself.

**Comment by dpizetta** [comment]
> Somehow I can't get running the python scripts on Window and Linux.

Do you have the log or the errors you faced? This can help us o provide better scripts. If you have, please, comment in the #226 so I can take into account when providing the compilation on the server.

>You can review it, and if you feel that lost formatting is a disaster let me know pls.

Can you provide only the scss file? Also, include your name in the AUTHORS  and add a CHANGES for a new version 2.8.1 too :) Thanks for helping us. 

@goanpeca do you have any other concern about this? Tks

**Comment by goanpeca** [comment]
Nope looks good!

**Comment by tsilia** [comment]
@dpizetta 
Updated the PR as per your request.

**Comment by dpizetta** [comment]
Thanks @tsilia  and @goanpeca.

**Pull request merged**
