### PR TITLE
Fix generating assets per operating system

### PR DESCRIPTION
**Pull request by ccordoba12**
The `shell` kwarg to `subprocess.call` can't be `True` in Posix systems.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dpizetta, I'm assuming you made `shell=True` because you needed to generate the assets on Windows before releasing QDarkStyle 3. This change makes things work again for Posix systems (i.e. Linux and macOS), where our scripts were broken due to that.

**Comment by ccordoba12** [comment]
Hey @dpizetta, have you had time to take a look at this?

**Comment by dpizetta** [comment]
Hey @ccordoba12, thanks for that.

**Comment by ccordoba12** [comment]
Thanks @dpizetta!

**Pull request merged**
