### PR TITLE
Able to get Qt API info from environment variable and solve tab problems

### LINKED ISSUE #59: Selected Tab color for QTabWidget slightly misleading
Take a look at the following picture and guess which Tab is selected in the 3 screenshots: http://i.imgur.com/CNWrggO.png

I found myself falling for the color scheme for the selected vs. unselected tabs. The darker background color is used for "selected", which I personally find to be slightly misleading, especially if you have 2 Tabs. I always feel like the lighter highlighted tab should be the one actually selected, as seen in the default windows theme and firefox.

As I already said, this is just my personal opinion and rather subjective, so let me know what you think. I'm sure I could get used to it.

### LINKED ISSUE #72: Tabs are pushed to right causing problems with east and west modes
See this example:

screenshot linux 2018-02-02 23 13 46

After removing:

```
QTabWidget::tab-bar {
    left: 5px; /* move to the right by 5px */
}
```

screenshot linux 2018-02-02 23 14 46

### PR DESCRIPTION
**Pull request by dpizetta**
- Add a function that get QT_API or PYQTGRAPH_QT_LIB and returns the right load_stylesheet function. It raises KeyError if not found;
- Add functions with names load_stylesheet_[pyside, pyside2, pyqt, pyqt5] to simplify;
- Messages with proper errors, warnings and infos are logged;
- Change to imperative mode the first sentence in docstring as recommended by pycodestyle;
- Correct PyQt5 example;
- Add QtPy example;
- Add PyQtGraph example;
- Add info in README;
- Fix comparison between QT_API and PYQTGRAPH_QT_LIB;
- Set selected tab background color to light one, fixes #59 ;
- Add a blue bar on selected tab, refs #59 ;
- Remove left space to fit tabs (mainly east and west), fixes #72.

### CODE REVIEW

**Comment by dpizetta** [comment]
Hey @ColinDuquesnoy, sorry for closing the other PR, I forgot to create a fresh branch, so this one gets all changes on it. I hope you enjoy. 

Also, if you agree, I can help administer this rep since you are not very interested in it nowadays. :)

**Comment by ColinDuquesnoy** [comment]
Thank you very much for your work! I like the new tab design 😄 

> Also, if you agree, I can help administer this rep since you are not very interested in it nowadays. :)

I agree. I was thinking to propose you to become a collaborator.

**Comment by ColinDuquesnoy** [comment]
If you agree, I can add you as a maintainer for the pypi package. I'd need your pypi username to add you as a maintainer.

**Comment by ColinDuquesnoy** [comment]
I added you as a maintainer on pypi. Thank you very much for your help!

**Comment by dpizetta** [comment]
Hi @ColinDuquesnoy, can you please, change my user on PyPI to "dpizetta", I solved the problem with my account (db issues), now I can use it again instead of "daniel.pizetta" (I will delete this one after your confirmation). Tks 
When you have time, no pressure :)

**Comment by ColinDuquesnoy** [comment]
Hi @dpizetta, this has been done :wink:

**Pull request merged**
