### PR TITLE
Improve light palette so there is better contrast between hovered and selected states

### PR DESCRIPTION
**Pull request by conradolandia**
Replaced some colors in `Gray` class, tones: B100 to B140, so they work better for the light theme.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conradolandia, could you post screenshots of how the light theme looks before and after this change? Thanks!

**Comment by conradolandia** [comment]
spyder_before
spyder_after

**Comment by conradolandia** [comment]
Before: 

spyder_before

After: 

spyder_after

**Comment by ccordoba12** [comment]
Thanks @conradolandia!

@dpizetta, these are screenshots of a new UI we're working on for Spyder 6 and where it's noticeable that the current light theme has serious issues to tell apart the hover and selected state of widgets. In addition, we checked that these changes don't introduce regressions for the dark theme.

I'll merge this one tomorrow by the end of the day unless you have any objections, of course.

**Pull request merged**
